[package]
name = "arielosbom"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-lock = "10.1.0"
cargo_metadata = "=0.22.0"
clap = { version = "4.5.48", features = ["derive"] }
chrono = { version = "0.4.42", features = ["serde"] }
semver = "=1.0.26"
serde = "=1.0.228"
serde_json = "=1.0.145"
